apiVersion: v1
kind: Service
metadata:
  name: hellochrissy
  labels:
    app: hellochrissy
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hellochrissy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellochrissy
  labels:
    app: hellochrissy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellochrissy
  template:
    metadata:
      labels:
        app: hellochrissy
    spec:
      containers:
      - name: hellochrissy
        image: cawifre/hellochrissy:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
